server:
  port: 8090

spring:
  application:
    name: betstream-api

# Esto desactiva el chequeo de base de datos al arrancar
autoconfigure:
  exclude:
    - org.springframework.boot.autoconfigure.r2dbc.R2dbcAutoConfiguration
    - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
    - org.springframework.boot.autoconfigure.amqp.RabbitAutoConfiguration
